--- 
 
spring.profiles: dev
server:
  port: 5700
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${instance-id:${random.value}}

spring:
  application:
    name: mobileadmin-service
  devtools:
    restart:
      enabled: true

  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    username: shavantha
    password: Welcome12!@
    url: jdbc:mysql://192.168.1.100:3306/administration_service_db_demo
#    192.168.1.100

    binders:
      rabbit1:
        type: rabbit
        environment:
          spring:
            rabbitmq:
              host: localhost
              port: 5672
              username: guest
              password: guest

  data:
    mongodb:
      database: audit-documents
      authentication-database: admin
      host: 192.168.1.100
      port: 1996
      username: shavantha
      password: Welcome12!@

      repositories:
        enabled: true # Enable Mongo repositories.
        #      uri: mongodb://localhost:3310/test
        # Mongo database URI. When set, host and
  #                port are ignored.'

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 5MB
      max-request-size: 10MB

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
#      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        #  generate_statistics: true
        jdbc:
          batch_size: 4
        order_inserts: true
  zipkin:
    base-url: http://192.168.1.100:9411

file:
  upload:
    location: /home/iihsolutions/images


resilience4j:
  circuitbreaker:
    instances:
      ehrService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30000
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 5
        allow-health-indicator-to-fail: true
        register-health-indicator: true

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
  endpoint:
    health:
      show-details: always

message: "from mobile admin dev"

--- 
 
spring.profiles: qa
server:
  port: 5800
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${instance-id:${random.value}}

spring:
  application:
    name: mobileadmin-service
  devtools:
    restart:
      enabled: true

  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    username: shavantha
    password: Welcome12!@
    url: jdbc:mysql://192.168.1.100:3306/administration_service_db_demo
#    192.168.1.100

    binders:
      rabbit1:
        type: rabbit
        environment:
          spring:
            rabbitmq:
              host: localhost
              port: 5672
              username: guest
              password: guest

  data:
    mongodb:
      database: audit-documents
      authentication-database: admin
      host: 192.168.1.100
      port: 1996
      username: shavantha
      password: Welcome12!@

      repositories:
        enabled: true # Enable Mongo repositories.
        #      uri: mongodb://localhost:3310/test
        # Mongo database URI. When set, host and
  #                port are ignored.'

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 5MB
      max-request-size: 10MB

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
#      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        #  generate_statistics: true
        jdbc:
          batch_size: 4
        order_inserts: true
  zipkin:
    base-url: http://192.168.1.100:9411

file:
  upload:
    location: /home/iihsolutions/images


resilience4j:
  circuitbreaker:
    instances:
      ehrService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30000
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 5
        allow-health-indicator-to-fail: true
        register-health-indicator: true

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
  endpoint:
    health:
      show-details: always

message: "from mobile admin qa"
      
