server:
  port: 5555

spring:
  application:
    name: Demo
  devtools:
    restart:
      enabled: true
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    username: root
    password: Welcome12!@
    url: jdbc:mysql://localhost:3306/test_db
 
 eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
   

message: "Good morning" 
