--- 
 
spring.profiles: dev
spring:
  application:
    name: audit-service
  devtools:
    restart:
      enabled: true
  main:
    allow-bean-definition-overriding: true

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    stream:
      bindings:
        riskackoutchannel:
          destination: riskackexchange
          group: riskackq
          binder: rabbit1
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
  data:
    mongodb:
      database: audit-documents
      authentication-database: admin
      host: localhost
#       username: shavantha
#       password: Welcome12!@
      port: 27017
      repositories:
        enabled: true

# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://localhost:8761/eureka
server:
  port: 3500
spring-doc:
  version: 1

token:
  secret: jguy5675hghgtrljkh
  
message: "good morning" 

--- 
 
spring.profiles: qa 

spring:
  application:
    name: audit-service
  devtools:
    restart:
      enabled: true
  main:
    allow-bean-definition-overriding: true

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    stream:
      bindings:
        riskackoutchannel:
          destination: riskackexchange
          group: riskackq
          binder: rabbit1
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
  data:
    mongodb:
      database: audit-documents
      authentication-database: admin
      host: localhost
#       username: shavantha
#       password: Welcome12!@
      port: 27017
      repositories:
        enabled: true

# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://localhost:8761/eureka
server:
  port: 3600
spring-doc:
  version: 1

token:
  secret: jguy5675hghgtrljkh
  
message: "Bad evening" 

